### ISSUE TITLE
Duplicated code 

### ISSUE THREAD

**Issue by yechielb2000** [Akiva-Grobman/python_socket_example#1]
Wouldn't it be better if you split the files to 2 folders ?
one for Pydantic, and one without Pydantic.

**Comment by Akiva-Grobman** [comment]
Great point! I await the PR :)

**Comment by yechielb2000** [comment]
Also, the code is duplicated the only difference is the Pydantic vs Json.

**Comment by Akiva-Grobman** [comment]
Indeed, this code was used to show an example use of pydantic and github.com was the easiest way to share it.
I appreciate your concern, but I think it'll be OK leaving it as is

**Comment by yechielb2000** [comment]
Ah ok ok
